FROM docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
RUN bin/elasticsearch-plugin install --batch repository-s3
RUN bin/elasticsearch-plugin install --batch analysis-kuromoji
RUN bin/elasticsearch-plugin install --batch analysis-icu
